#### Import Library

In [1]:
import numpy as np

1. Write a NumPy program to create a 5x5 array with random values and find the minimum and maximum values.

In [2]:
# Create the random array 5x5
array_1 = np.random.rand(5, 5)
array_1

array([[0.03132343, 0.41062172, 0.64939218, 0.56210044, 0.4731147 ],
       [0.64747597, 0.20984036, 0.85718548, 0.70787429, 0.00275631],
       [0.51588799, 0.10341337, 0.77299712, 0.44251641, 0.96302691],
       [0.51760792, 0.2725623 , 0.89166985, 0.15570873, 0.6041456 ],
       [0.1144692 , 0.36547992, 0.34955006, 0.7166442 , 0.985266  ]])

In [3]:
# Find the maximum and minimum value
print(f"Maximum value of the array_1: {np.max(array_1)}")
print(f"Minimum value of the array_1: {np.min(array_1)}")

Maximum value of the array_1: 0.9852659998978901
Minimum value of the array_1: 0.002756310275335294


2. Write a NumPy program to create a random 10x4 array and extract the first five rows of the array and store them into a variable.

In [4]:
# Create the random array 10x4
array_2 = np.random.rand(10, 4)
array_2

array([[0.17721937, 0.89001937, 0.97653172, 0.23509488],
       [0.0517094 , 0.3095999 , 0.1428093 , 0.59022516],
       [0.94102449, 0.48124189, 0.34772811, 0.0721409 ],
       [0.13507308, 0.49465797, 0.38963413, 0.0358029 ],
       [0.76543762, 0.23497062, 0.32421815, 0.65882024],
       [0.44916998, 0.0379589 , 0.40060233, 0.3890994 ],
       [0.18350419, 0.79636303, 0.99433867, 0.65153998],
       [0.13766616, 0.83007528, 0.76013032, 0.36523877],
       [0.9797893 , 0.96493995, 0.82760085, 0.6820059 ],
       [0.55736322, 0.15068696, 0.860666  , 0.63928579]])

In [5]:
# Extract the five first rows of array_2
f_five_rows = array_2[:5, :]
f_five_rows

array([[0.17721937, 0.89001937, 0.97653172, 0.23509488],
       [0.0517094 , 0.3095999 , 0.1428093 , 0.59022516],
       [0.94102449, 0.48124189, 0.34772811, 0.0721409 ],
       [0.13507308, 0.49465797, 0.38963413, 0.0358029 ],
       [0.76543762, 0.23497062, 0.32421815, 0.65882024]])

3. Write a NumPy program to create random vector of size 15 and replace the maximum value by -1.

In [6]:
# Create the random vector 15
vector = np.random.random(15)
vector, vector.shape

(array([0.92546959, 0.02389043, 0.55167065, 0.68646546, 0.01885392,
        0.43590663, 0.10881927, 0.14515907, 0.99579142, 0.75821183,
        0.76666786, 0.46632929, 0.95670062, 0.93530852, 0.49725453]),
 (15,))

In [7]:
# Maximum value and index
np.max(vector), np.argmax(vector)

(0.9957914198287979, 8)

In [8]:
# Replace the maximum value by -1
vector[np.argmax(vector)] = -1
vector

array([ 0.92546959,  0.02389043,  0.55167065,  0.68646546,  0.01885392,
        0.43590663,  0.10881927,  0.14515907, -1.        ,  0.75821183,
        0.76666786,  0.46632929,  0.95670062,  0.93530852,  0.49725453])

4. normalize an array so the values range exactly between 0 and 1?

In [9]:
# Create an array
array_3 = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15]
])
array_3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [10]:
array_3_normalize = (array_3 - np.min(array_3)) / (np.max(array_3) - np.min(array_3))
array_3_normalize

array([[0.        , 0.07142857, 0.14285714, 0.21428571, 0.28571429],
       [0.35714286, 0.42857143, 0.5       , 0.57142857, 0.64285714],
       [0.71428571, 0.78571429, 0.85714286, 0.92857143, 1.        ]])

5. convert an array of arrays into a flat 1d array

In [11]:
# Create an array
array_4 = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])
array_4

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
array_4.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])