### Import libraries

In [1]:
import numpy as np

### How to create an 1d_array

In [2]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [3]:
a.dtype

dtype('int64')

#### set dtype explicitly

In [4]:
a = np.array([1, 2, 3, 4, 5], dtype=np.float64)
a

array([1., 2., 3., 4., 5.])

In [5]:
a.ndim, a.shape, a.size, a.dtype, a.sum(), a.argsort()

(1, (5,), 5, dtype('float64'), 15.0, array([0, 1, 2, 3, 4]))

In [6]:
a = a.astype(np.float32) # a.astype('float32')
a

array([1., 2., 3., 4., 5.], dtype=float32)

In [7]:
a.dtype

dtype('float32')

### How to create an nd_array

In [8]:
lst = [
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10]
]
lst

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [9]:
b = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10]
], dtype=np.float64)
b

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [10]:
b.dtype

dtype('float64')

In [11]:
b.ndim, b.shape, b.size

(2, (2, 5), 10)

### Reshape

In [12]:
array = np.array([
    [1, 2, 3, 4, 5, 6],
    [7, 8, 9, 10, 11, 12]
], dtype=np.float64)
array

array([[ 1.,  2.,  3.,  4.,  5.,  6.],
       [ 7.,  8.,  9., 10., 11., 12.]])

In [13]:
array.shape

(2, 6)

In [14]:
np.reshape(array, newshape=[6, 2])

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.],
       [ 9., 10.],
       [11., 12.]])

In [15]:
array.size

12

In [16]:
reshaped_array = np.reshape(array, newshape=[2, 3, -1])
reshaped_array

array([[[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.]],

       [[ 7.,  8.],
        [ 9., 10.],
        [11., 12.]]])

In [17]:
reshaped_array.shape

(2, 3, 2)

In [18]:
reshaped_array = np.reshape(array, newshape=[2,-1,2])
reshaped_array

array([[[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.]],

       [[ 7.,  8.],
        [ 9., 10.],
        [11., 12.]]])

In [19]:
reshaped_array.shape

(2, 3, 2)

### Methods in numpy

In [20]:
np.zeros(shape=(3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np.empty((4, 4))

array([[6.91791841e-310, 4.65392802e-310, 4.65392806e-310,
        6.91791841e-310],
       [2.42766858e-154, 1.03758390e+243, 1.97134294e-153,
        6.01346954e-154],
       [2.38338680e+180, 1.46923335e+195, 9.82391603e+252,
        1.13513305e-153],
       [4.63362100e+228, 7.20354678e+159, 1.52394767e-258,
        6.01347002e-154]])

In [22]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [23]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [24]:
np.random.standard_normal((2, 3))

array([[ 0.01367217, -1.37286658,  0.72842285],
       [-0.27955643,  0.36715627,  0.48412854]])

In [25]:
a = np.random.multivariate_normal(mean=[1, 1], cov=0.01 * np.eye(2), size=(50, ))
a.shape

(50, 2)

### Axis

In [26]:
array = np.random.standard_normal((2, 3))
array

array([[-0.3652248 ,  1.12860603,  1.54983853],
       [ 0.1823326 , -0.73622351, -0.44201354]])

In [27]:
np.sum(array, axis=1)

array([ 2.31321976, -0.99590446])

In [28]:
sum([-0.79441283,  0.24852512, -1.56639577]), sum([ 1.17892706,  1.26351743, -0.04678119])

(-2.11228348, 2.3956633)

In [29]:
np.mean(array, axis=0)

array([-0.0914461 ,  0.19619126,  0.55391249])

### Stacking

In [30]:
a = np.random.standard_normal((2, 3))
b = np.random.standard_normal((2, 3))

In [31]:
np.vstack([a, b]) # number of columns does not change...

array([[-0.93114184,  0.45393007,  0.4671786 ],
       [-0.35262339, -1.04056102,  0.15331778],
       [ 0.24035088, -0.25461487, -0.17952994],
       [-1.72236869, -0.13470688, -0.05099277]])

In [32]:
np.hstack([a, b]) # number of rows does not change...

array([[-0.93114184,  0.45393007,  0.4671786 ,  0.24035088, -0.25461487,
        -0.17952994],
       [-0.35262339, -1.04056102,  0.15331778, -1.72236869, -0.13470688,
        -0.05099277]])

In [33]:
np.concatenate([a, b])

array([[-0.93114184,  0.45393007,  0.4671786 ],
       [-0.35262339, -1.04056102,  0.15331778],
       [ 0.24035088, -0.25461487, -0.17952994],
       [-1.72236869, -0.13470688, -0.05099277]])

In [34]:
np.concatenate([a, b], axis=1)

array([[-0.93114184,  0.45393007,  0.4671786 ,  0.24035088, -0.25461487,
        -0.17952994],
       [-0.35262339, -1.04056102,  0.15331778, -1.72236869, -0.13470688,
        -0.05099277]])

In [35]:
a.transpose()

array([[-0.93114184, -0.35262339],
       [ 0.45393007, -1.04056102],
       [ 0.4671786 ,  0.15331778]])

In [36]:
a.T

array([[-0.93114184, -0.35262339],
       [ 0.45393007, -1.04056102],
       [ 0.4671786 ,  0.15331778]])

In [37]:
np.save('./Output/example.npy', a)

In [38]:
a1 = np.load('./Output/example.npy')

In [39]:
a1

array([[-0.93114184,  0.45393007,  0.4671786 ],
       [-0.35262339, -1.04056102,  0.15331778]])

In [40]:
np.allclose(a, a1)

True

### Check the speed of arrays

In [41]:
a = np.linspace(0, 100, 1000000)
b = np.linspace(0, 100, 1000000)

In [42]:
a.size

1000000

In [43]:
def get_dot(a,b):
    c = 0
    for i in range(1000000):
        c += a[i] * b[i]
    return c

In [44]:
%timeit get_dot(a,b)

224 ms ± 9.65 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [45]:
result = np.dot(a,b)
result

3333335000.0016665

In [46]:
get_dot(a, b)

3333335000.001634

In [47]:
%timeit np.dot(a,b)

856 µs ± 197 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


### Broadcasting

In [48]:
v = np.linspace(0, 10, 5)
v + 1

array([ 1. ,  3.5,  6. ,  8.5, 11. ])

In [49]:
ones = np.ones((6, 5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [50]:
twos = np.ones((6, 1)) * 2
twos

array([[2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.]])

In [51]:
ones.shape, twos.shape

((6, 5), (6, 1))

In [52]:
ones + twos

array([[3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.]])