### Import libraries

In [1]:
import numpy as np

In [2]:
v = np.linspace(0, 10, 5)
v

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [3]:
v[0]

0.0

In [4]:
v[1]

2.5

In [5]:
v[-1]

10.0

In [6]:
v[5]

IndexError: index 5 is out of bounds for axis 0 with size 5

In [7]:
vv = np.random.random((5, 4))
vv

array([[0.61496103, 0.66162142, 0.64390886, 0.07800552],
       [0.58669378, 0.7641158 , 0.38391842, 0.12188874],
       [0.0339398 , 0.32137202, 0.12590626, 0.98818264],
       [0.17155471, 0.56802078, 0.73969829, 0.23914894],
       [0.43847372, 0.110851  , 0.37736834, 0.82503935]])

In [8]:
vv[0, 0]

0.6149610348578526

In [9]:
vv[4, 3]

0.8250393515463199

In [10]:
ll = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
ll

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
ll[1, 2]

TypeError: list indices must be integers or slices, not tuple

In [12]:
ll[1][2]

6

In [13]:
v[2:4]

array([5. , 7.5])

In [14]:
vv[2:5, 1]

array([0.32137202, 0.56802078, 0.110851  ])

In [15]:
vv[2:5, 1:2]

array([[0.32137202],
       [0.56802078],
       [0.110851  ]])

In [16]:
vv[2:-1, :]

array([[0.0339398 , 0.32137202, 0.12590626, 0.98818264],
       [0.17155471, 0.56802078, 0.73969829, 0.23914894]])

In [17]:
vv[:, ::2]

array([[0.61496103, 0.64390886],
       [0.58669378, 0.38391842],
       [0.0339398 , 0.12590626],
       [0.17155471, 0.73969829],
       [0.43847372, 0.37736834]])

### Mutable

In [18]:
v2 = v[2:4]
v2

array([5. , 7.5])

In [19]:
v2[0] = 0

In [20]:
v

array([ 0. ,  2.5,  0. ,  7.5, 10. ])

In [21]:
v3 = v[2:4].copy()

In [22]:
v3[0] = 1

In [23]:
v

array([ 0. ,  2.5,  0. ,  7.5, 10. ])

### Boolean Mask

In [24]:
v

array([ 0. ,  2.5,  0. ,  7.5, 10. ])

In [25]:
v[[0, 2, 4]]

array([ 0.,  0., 10.])

In [26]:
bool_index = v > 0
bool_index

array([False,  True, False,  True,  True])

In [27]:
v[bool_index]

array([ 2.5,  7.5, 10. ])

In [28]:
vv

array([[0.61496103, 0.66162142, 0.64390886, 0.07800552],
       [0.58669378, 0.7641158 , 0.38391842, 0.12188874],
       [0.0339398 , 0.32137202, 0.12590626, 0.98818264],
       [0.17155471, 0.56802078, 0.73969829, 0.23914894],
       [0.43847372, 0.110851  , 0.37736834, 0.82503935]])

In [29]:
vv[vv > 0.5] = vv[vv > 0.5] * 2

In [30]:
vv

array([[1.22992207, 1.32324285, 1.28781771, 0.07800552],
       [1.17338756, 1.52823159, 0.38391842, 0.12188874],
       [0.0339398 , 0.32137202, 0.12590626, 1.97636528],
       [0.17155471, 1.13604156, 1.47939658, 0.23914894],
       [0.43847372, 0.110851  , 0.37736834, 1.6500787 ]])

In [31]:
vv[vv > 0.5] = 0.0
vv

array([[0.        , 0.        , 0.        , 0.07800552],
       [0.        , 0.        , 0.38391842, 0.12188874],
       [0.0339398 , 0.32137202, 0.12590626, 0.        ],
       [0.17155471, 0.        , 0.        , 0.23914894],
       [0.43847372, 0.110851  , 0.37736834, 0.        ]])

In [32]:
v

array([ 0. ,  2.5,  0. ,  7.5, 10. ])

In [33]:
v[[0, 3]] = [4, 5]
v

array([ 4. ,  2.5,  0. ,  5. , 10. ])