### Import libraries

In [1]:
import numpy as np

In [2]:
array = np.random.standard_normal((4, 5))
array

array([[ 1.02300751, -1.30092561,  1.94294064, -0.59422381,  0.11086229],
       [-0.71760955,  0.22496937,  1.33278814, -0.76823209, -0.46006862],
       [ 0.96909267, -1.23439901,  0.8787908 , -0.7723703 , -1.06447984],
       [-1.30054851, -0.74956279, -0.44833949, -0.29286497,  0.72749396]])

In [3]:
array.reshape((20, ))

array([ 1.02300751, -1.30092561,  1.94294064, -0.59422381,  0.11086229,
       -0.71760955,  0.22496937,  1.33278814, -0.76823209, -0.46006862,
        0.96909267, -1.23439901,  0.8787908 , -0.7723703 , -1.06447984,
       -1.30054851, -0.74956279, -0.44833949, -0.29286497,  0.72749396])

In [4]:
x = np.linspace(0, 5, 15)
sinx = np.sin(x)
cosx = np.cos(x)
sinx, cosx

(array([ 0.        ,  0.34959881,  0.6550779 ,  0.8778855 ,  0.98990308,
         0.97699389,  0.84078711,  0.59847214,  0.2806294 , -0.07262906,
        -0.41672165, -0.70822356, -0.91034694, -0.99758364, -0.95892427]),
 array([ 1.        ,  0.9368995 ,  0.75556135,  0.4788706 ,  0.1417459 ,
        -0.21326728, -0.5413659 , -0.80114362, -0.9598162 , -0.99735902,
        -0.90903414, -0.70598824, -0.41384591, -0.06947582,  0.28366219]))

In [5]:
np.dot(sinx, cosx)

1.096139366513961

In [6]:
ones = np.ones((5, ))
ones

array([1., 1., 1., 1., 1.])

In [7]:
line_space = np.linspace(-2, 2, 5)
line_space

array([-2., -1.,  0.,  1.,  2.])

In [8]:
rl = np.outer(ones, line_space)
rl

array([[-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.]])

### np.dot

In [9]:
ones = np.ones((6, 5)) * 3
ones

array([[3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.]])

In [10]:
ones.shape

(6, 5)

In [11]:
ones_reshaped = ones.reshape(5, 6)
ones_reshaped

array([[3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3.]])

In [12]:
np.dot(ones_reshaped , ones)

array([[54., 54., 54., 54., 54.],
       [54., 54., 54., 54., 54.],
       [54., 54., 54., 54., 54.],
       [54., 54., 54., 54., 54.],
       [54., 54., 54., 54., 54.]])

In [13]:
A = np.array([
    [1, 2],
    [3, 5],
    [7, 6]
])
p = np.diag([5, 5, 5])
l = np.array([7, 3, 2]).reshape((3, 1))

In [14]:
np.dot(np.dot(np.dot(np.linalg.inv(np.dot(np.dot(A.T, p), A)), A.T), p), l)

array([[-1.32485876],
       [ 1.83333333]])

### Numpy where

In [15]:
array = np.array([1, 2, 3, 4])
rows = np.where(array >= 2.5)
array[rows]

array([3, 4])

In [16]:
t = np.array([
    [1, 2, 3, 'foo'],
    [2, 3, 4, 'bar'],
    [5, 6, 7, 'hello'],
    [8, 9, 1, 'bar']
])
t

array([['1', '2', '3', 'foo'],
       ['2', '3', '4', 'bar'],
       ['5', '6', '7', 'hello'],
       ['8', '9', '1', 'bar']], dtype='<U21')

In [17]:
rows, cols = np.where(t == 'bar')
t[rows]

array([['2', '3', '4', 'bar'],
       ['8', '9', '1', 'bar']], dtype='<U21')

In [18]:
rows, cols

(array([1, 3]), array([3, 3]))

In [19]:
array = np.random.standard_normal((5, 5, 3))
array

array([[[ 0.633759  ,  0.7103308 ,  0.90678985],
        [-0.69161945,  1.23615247,  0.66952832],
        [ 0.20701374, -0.76835813, -1.70808611],
        [ 0.35791232, -0.37270567,  0.15066041],
        [ 0.61112044,  0.28877807, -1.7395657 ]],

       [[-0.55971668,  1.63347374,  0.33013999],
        [ 0.59442012, -0.07556218, -2.06853164],
        [ 0.99574266,  0.63369286, -0.46416482],
        [-0.36702993, -0.84967407,  0.30153776],
        [-0.67802922, -0.31548178,  1.10717178]],

       [[-0.82038278, -1.50689976, -0.76176671],
        [-2.2593054 , -0.58483709, -1.49368653],
        [-0.0740965 ,  0.66812697, -0.52157792],
        [ 0.52756394,  1.32032059,  0.61965218],
        [ 0.01987798, -0.67588517,  0.97541127]],

       [[ 1.20735263,  0.70421268, -0.43702273],
        [ 0.2060814 , -0.39052401,  0.12814961],
        [-0.07880603, -0.13204532, -1.18715842],
        [ 0.72185538,  0.15463189,  1.47811264],
        [ 0.35613855,  0.41686257,  1.18536554]],

       [[ 0.

In [20]:
rows, cols, heights = np.where(array >= 1)
array[rows, cols, heights]

array([1.23615247, 1.63347374, 1.10717178, 1.32032059, 1.20735263,
       1.47811264, 1.18536554, 1.55209902, 1.52208609])

In [21]:
rows, cols, heights

(array([0, 1, 1, 2, 3, 3, 3, 4, 4]),
 array([1, 0, 4, 3, 0, 3, 4, 3, 3]),
 array([1, 1, 2, 1, 0, 2, 2, 1, 2]))