# TensorFlow
    TensorFlow is an open source library for numerical computation using data flow graphs

TensorFlow can be described with a data model, a programming model, and an execution
model:
* <b>Data</b> model comprises of tensors, that are the basic data units created,
manipulated, and saved in a TensorFlow program.
* <b>Programming</b> model comprises of data flow graphs or computation graphs.
Creating a program in TensorFlow means building one or more TensorFlow
computation graphs.
* <b>Execution</b> model consists of firing the nodes of a computation graph in a
sequence of dependence. The execution starts by running the nodes that are
directly connected to inputs and only depend on inputs being present.

TensorFlow APIs or libraries are divided into two levels:
* <b>Lower-level library</b>: The lower level library, also known as TensorFlow core,
provides very fine-grained lower level functionality, thereby offering complete
control on how to use and implement the library in the models. We will cover
TensorFlow core in this chapter.
* <b>Higher-level libraries</b>: These libraries provide high-level functionalities and are
comparatively easier to learn and implement in the models. Some of the libraries
include TF Estimators, TFLearn, TFSlim, Sonnet, and Keras. We will cover some
of these libraries in the next chapter.

# TensorFlow Core
A tensor can have any number of dimensions:
* <b>scalar</b>: a zero-dimensional collection(tensor rank 0)
* <b>vector</b>: a one-dimensional collection(tensor rank 1)
* <b>matrix</b>: a two-dimensional collection(tensor rank 2)
* <b>tensor</b>: multidimensional collection(tensor rank >2)


## Tensors
    * Constants
    * Placeholders
    * Operations
    * Creating tensors from Python objects
    * Variables
    * Tensors generated from library functions

In [11]:
import tensorflow as tf
import numpy as np

import warnings
warnings.simplefilter("ignore")

# Constants

In [10]:
c1 = tf.constant(value=5, name='x')
c2 = tf.constant(value=6.0, name='x')
c3 = tf.constant(value=7.0, dtype=tf.float32, name='z')
print('c1 (x): ', c1)
print('c2 (y): ', c2)
print('c3 (z): ', c3)

c1 (x):  tf.Tensor(5, shape=(), dtype=int32)
c2 (y):  tf.Tensor(6.0, shape=(), dtype=float32)
c3 (z):  tf.Tensor(7.0, shape=(), dtype=float32)


<img src="./Images/data_types.PNG">

# Operations

In [3]:
op1 = tf.add(c2, c3)
op2 = tf.multiply(c2, c3)
print('op1 : ', op1)
print('op2 : ', op2)

op1 :  tf.Tensor(13.0, shape=(), dtype=float32)
op2 :  tf.Tensor(42.0, shape=(), dtype=float32)


<img src="./Images//operations.PNG">

# Creating Tensors from Existing Objects

## 0-Dimensional Tensors (Scalars)

In [4]:
tf_t = tf.convert_to_tensor(5.0, dtype=tf.float64)

print('tf_t : ', tf_t)

tf_t :  tf.Tensor(5.0, shape=(), dtype=float64)


## 1-Dimensional Tensors (Vectors)

In [5]:
a1dim = np.array([1, 2, 3, 4, 5.99])
print("a1dim Shape : ", a1dim.shape)

tf_t = tf.convert_to_tensor(a1dim, dtype=tf.float64)

print('tf_t : ', tf_t)
print('tf_t[0] : ', tf_t[0])
print('tf_t[0] : ', tf_t[2])

a1dim Shape :  (5,)
tf_t :  tf.Tensor([1.   2.   3.   4.   5.99], shape=(5,), dtype=float64)
tf_t[0] :  tf.Tensor(1.0, shape=(), dtype=float64)
tf_t[0] :  tf.Tensor(3.0, shape=(), dtype=float64)


## 2-Dimensional Tensors (Matrices)

In [6]:
a2dim = np.array([(1, 2, 3, 4, 5.99),
                  (2, 3, 4, 5, 6.99),
                  (3, 4, 5, 6, 7.99)
                  ])
print("a2dim Shape : ", a2dim.shape)

tf_t = tf.convert_to_tensor(a2dim, dtype=tf.float64)

print('tf_t : ', tf_t)
print('tf_t[0][0] : ', tf_t[0][0])
print('tf_t[1][2] : ', tf_t[1][2])

a2dim Shape :  (3, 5)
tf_t :  tf.Tensor(
[[1.   2.   3.   4.   5.99]
 [2.   3.   4.   5.   6.99]
 [3.   4.   5.   6.   7.99]], shape=(3, 5), dtype=float64)
tf_t[0][0] :  tf.Tensor(1.0, shape=(), dtype=float64)
tf_t[1][2] :  tf.Tensor(4.0, shape=(), dtype=float64)


## 3-Dimensional Tensors

In [7]:
a3dim = np.array([[[1, 2],
                   [3, 4]
                   ],
                  [[5, 6],
                   [7, 8]
                   ]
                  ])
print("a3dim Shape : ", a3dim.shape)

tf_t = tf.convert_to_tensor(a3dim, dtype=tf.float64)

print('tf_t : ', tf_t)
print('tf_t[0][0][0] : ', tf_t[0][0][0])
print('tf_t[1][1][1] : ', tf_t[1][1][1])

a3dim Shape :  (2, 2, 2)
tf_t :  tf.Tensor(
[[[1. 2.]
  [3. 4.]]

 [[5. 6.]
  [7. 8.]]], shape=(2, 2, 2), dtype=float64)
tf_t[0][0][0] :  tf.Tensor(1.0, shape=(), dtype=float64)
tf_t[1][1][1] :  tf.Tensor(8.0, shape=(), dtype=float64)


# Variables
In TensorFlow, variables are tensor objects that hold values that can be modified during the
execution of the program.

In [8]:
# Assume Linear Model y = w * x + b
# Define model parameters
w = tf.Variable([.3], tf.float32, name='w')
b = tf.Variable([-.3], tf.float32)

print("w:", w)
print("b:", b)

w: <tf.Variable 'w:0' shape=(1,) dtype=float32, numpy=array([0.3], dtype=float32)>
b: <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([-0.3], dtype=float32)>


<img src="./Images//variables_placeholders.PNG">

# Creating Tensors from Library Functions

In [9]:
a = tf.zeros((100,))